<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<AppConfig>App.config</AppConfig>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AssemblyName>PugTools</AssemblyName>
		<Authors />
		<BinDir>..\..\..\Bin\$(Configuration)\</BinDir>
		<Company />
		<Copyright>Copyright ©  2012</Copyright>
		<Description>A collection of SWTOR datamining tools</Description>
		<NeutralLanguage>en-US</NeutralLanguage>
		<OutputType>WinExe</OutputType>
		<Platforms>x64</Platforms>
		<PlatformTarget>x64</PlatformTarget>
		<ProduceReferenceAssembly>false</ProduceReferenceAssembly>
		<RootNamespace>PugTools</RootNamespace>
		<StartupObject>PugTools.Program</StartupObject>
		<TargetFramework>net6.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>portable</DebugType>
		<DefineConstants>TRACE;DEBUG</DefineConstants>
		<ErrorReport>prompt</ErrorReport>
		<NoWarn>IDE1006</NoWarn>
		<OutputPath>$(BaseOutputPath)$(Configuration)</OutputPath>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>

	<ItemGroup>
	  <EmbeddedResource Remove="Forms\Tools_UI.resx" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Hash\hashes_filename.bin.gz" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="Shaders\GR2.fx" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="Shaders\World.fx" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="Tools\packed_codebooks_aoTuV_603.bin" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="Tools\revorb.exe" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="Tools\ww2ogg.exe" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="WorldAreaNames.xml" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>true</DesignTime>
			<AutoGen>true</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="ColorCode">
			<HintPath>..\..\Include\ColorCode.dll</HintPath>
		</Reference>
		<Reference Include="SlimDX">
			<HintPath>..\..\Libraries\SlimDX.NET\Include\SlimDX.dll</HintPath>
		</Reference>
		<Reference Include="SpriteTextRenderer">
			<HintPath>..\..\Libraries\SlimDX.NET\Include\SpriteTextRenderer.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MySql.Data" Version="8.0.28" />
		<PackageReference Include="NAudio.Core" Version="2.0.0" />
		<PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
		<PackageReference Include="NAudio.WinMM" Version="2.0.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
		<PackageReference Include="NVorbis" Version="0.10.4" />
		<PackageReference Include="SharpZipLib" Version="1.3.3" />
		<PackageReference Include="ZstdSharp.Port" Version="0.8.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Controls\HexBox\HexBox.csproj" />
		<ProjectReference Include="..\..\Controls\ObjectListView\ObjectListView.csproj" />
		<ProjectReference Include="..\..\Libraries\DevIL.NET\DevIL.NET.csproj" />
		<ProjectReference Include="..\..\Libraries\GomLib\GomLib.csproj" />
		<ProjectReference Include="..\..\Libraries\HashDictionary\HashDictionary.csproj" />
		<ProjectReference Include="..\..\Libraries\SlimDX.NET\SlimDX.NET.csproj" />
		<ProjectReference Include="..\..\Libraries\TorArchive\TorArchive.csproj" />
	</ItemGroup>

	<Target Name="Post Build" AfterTargets="Build" Condition="Exists('$(SolutionDir)..\..\AppHostPatcher\AppHostPatcher.exe')">
		<MakeDir Condition="!Exists('$BinDir')" Directories="$(BinDir)" />

		<MakeDir Condition="!Exists('$(BinDir)Hash')" Directories="$(BinDir)Hash" />
		<Copy SourceFiles="$(ProjectDir)Hash\hashes_filename.bin.gz" DestinationFolder="$(BinDir)Hash" />

		<MakeDir Condition="!Exists('$(BinDir)Libraries')" Directories="$(BinDir)Libraries" />
		<ItemGroup>
			<DLLs Include="$(TargetDir)*.dll" />
			<PDBs Include="$(TargetDir)*.pdb" />
			<XMLs Include="$(TargetDir)*.xml" />
			<Tools Include="$(ProjectDir)Tools\*.*" />
		</ItemGroup>
		<Copy SourceFiles="@(DLLs)" DestinationFolder="$(BinDir)Libraries" />
		<Copy SourceFiles="@(PDBs)" DestinationFolder="$(BinDir)Libraries" />
		<Copy SourceFiles="@(XMLs)" DestinationFolder="$(BinDir)Libraries" />
		<!--
		<Copy SourceFiles="$(SolutionDir)Libraries\DevIL.NET\Include\$(Platform)\DevIL.dll" DestinationFolder="$(BinDir)Libraries" />
		<Copy SourceFiles="$(SolutionDir)Libraries\DevIL.NET\Include\$(Platform)\ILU.dll" DestinationFolder="$(BinDir)Libraries" />
		-->
		<Copy SourceFiles="$(TargetDir)PugTools.dll.config" DestinationFolder="$(BinDir)Libraries" />
		<Copy SourceFiles="$(TargetDir)PugTools.runtimeconfig.json" DestinationFolder="$(BinDir)Libraries" />

		<MakeDir Condition="!Exists('$(BinDir)Shaders')" Directories="$(BinDir)Shaders" />
		<Copy SourceFiles="$(ProjectDir)Shaders\GR2.fx" DestinationFolder="$(BinDir)Shaders" />
		<Copy SourceFiles="$(ProjectDir)Shaders\World.fx" DestinationFolder="$(BinDir)Shaders" />

		<Copy SourceFiles="$(ProjectDir)WorldAreaNames.xml" DestinationFolder="$(BinDir)" SkipUnchangedFiles="true" />

		<MakeDir Condition="!Exists('$(BinDir)Tools')" Directories="$(BinDir)Tools" />
		<Copy SourceFiles="@(Tools)" DestinationFolder="$(BinDir)Tools" />

		<Copy SourceFiles="$(TargetDir)PugTools.exe" DestinationFolder="$(BinDir)" />

		<Exec Command="$(SolutionDir)..\..\AppHostPatcher\AppHostPatcher.exe $(BinDir)PugTools.exe -d Libraries" />
	</Target>

	<Target Name="Post Clean" AfterTargets="Clean">
		<RemoveDir Condition="Exists('$(BinDir)')" Directories="$(BinDir)" />
	</Target>

</Project>
